apiVersion: apps/v1
kind: Deployment
metadata:
  name: portsite-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: msp2020xxxx/portsite:v1
          imagePullPolicy: Always
          ports:

            - containerPort: 80

